language: node_js
node_js:
  - "16.6.1"
script:
  - echo "Deploying!"
  - npm install
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token 1//0gz7Nz6JfRH55CgYIARAAGBASNgF-L9Ir1LLM0Ewn4UnL-FGTJKxHXzrGYJ6YzcFW-L6M0akcvK3xHW7zt_mzljgPH2E6g5xgEQ